name: Sync NeoDB Data

on:
  schedule:
    - cron: '0 2 * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  neodb:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 允许写入仓库内容
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整历史记录，支持增量下载

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.0

      - name: Install dependencies
        run: pnpm install

      - name: Sync NeoDB Data
        env:
          NEODB_API_SECRET: ${{ secrets.NEODB_API_SECRET }}
        run: |
          pnpm run neodb

      - name: Display download statistics
        run: |
          echo "=== NeoDB Data Sync Statistics ==="
          if [ -d ".data/neodb" ]; then
            echo "NeoDB directory contents:"
            ls -la .data/neodb/
            if [ -d ".data/neodb/cover" ]; then
              echo "Cover images count: $(ls -1 .data/neodb/cover | wc -l)"
              echo "Latest cover images:"
              ls -lt .data/neodb/cover | head -5
            fi
          else
            echo "No neodb directory found"
          fi

      - name: Check for changes
        id: check_changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changes=true" >> $GITHUB_OUTPUT
            echo "Changed files:"
            git status --porcelain
          else
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "No changes detected"
          fi

      - name: Commit and push changes to current repo
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .data/neodb/
          git commit -m "action(data): auto update neodb data [skip ci]"
          git push

      - name: Clone target repo
        uses: actions/checkout@v4
        with:
          repository: hsinyau/static
          path: static
          token: ${{ secrets.GH_SECRET }}

      - name: Sync to target repo
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          cp -r .data/neodb/* ./static/neodb/
          cd static
          git config --local user.email "hsinyau@qq.com"
          git config --local user.name "hsinyau"
          git add ./neodb/
          git commit -m "action(data): auto update neodb data"
          git push
